export const COUNTRIES = [{ "code": "US", "name": "United States", "region": "North America", "flag": "us" },
{ "code": "CN", "name": "China", "region": "Asia", "flag": "cn" },
{ "code": "GB", "name": "United Kingdom", "region": "Europe", "flag": "gb" },
{ "code": "DE", "name": "Germany", "region": "Europe", "flag": "de" },
{ "code": "FR", "name": "France", "region": "Europe", "flag": "fr" },
{ "code": "CA", "name": "Canada", "region": "North America", "flag": "ca" },
{ "code": "AU", "name": "Australia", "region": "Oceania", "flag": "au" },
{ "code": "JP", "name": "Japan", "region": "Asia", "flag": "jp" },
{ "code": "KR", "name": "South Korea", "region": "Asia", "flag": "kr" },
{ "code": "IN", "name": "India", "region": "Asia", "flag": "in" },
{ "code": "BR", "name": "Brazil", "region": "South America", "flag": "br" },
{ "code": "MX", "name": "Mexico", "region": "North America", "flag": "mx" },
{ "code": "ZA", "name": "South Africa", "region": "Africa", "flag": "za" },
{ "code": "NG", "name": "Nigeria", "region": "Africa", "flag": "ng" },
{ "code": "KE", "name": "Kenya", "region": "Africa", "flag": "ke" },
{ "code": "GH", "name": "Ghana", "region": "Africa", "flag": "gh" },
{ "code": "CM", "name": "Cameroon", "region": "Africa", "flag": "cm" },
{ "code": "UG", "name": "Uganda", "region": "Africa", "flag": "ug" },
{ "code": "TZ", "name": "Tanzania", "region": "Africa", "flag": "tz" },
{ "code": "RW", "name": "Rwanda", "region": "Africa", "flag": "rw" },
{ "code": "ET", "name": "Ethiopia", "region": "Africa", "flag": "et" },
{ "code": "AE", "name": "United Arab Emirates", "region": "Middle East", "flag": "ae" },
{ "code": "SA", "name": "Saudi Arabia", "region": "Middle East", "flag": "sa" },
{ "code": "TR", "name": "Turkey", "region": "Europe", "flag": "tr" },
{ "code": "IT", "name": "Italy", "region": "Europe", "flag": "it" },
{ "code": "ES", "name": "Spain", "region": "Europe", "flag": "es" },
{ "code": "NL", "name": "Netherlands", "region": "Europe", "flag": "nl" },
{ "code": "BE", "name": "Belgium", "region": "Europe", "flag": "be" },
{ "code": "SE", "name": "Sweden", "region": "Europe", "flag": "se" },
{ "code": "CH", "name": "Switzerland", "region": "Europe", "flag": "ch" },
{ "code": "SG", "name": "Singapore", "region": "Asia", "flag": "sg" },
{ "code": "MY", "name": "Malaysia", "region": "Asia", "flag": "my" },
{ "code": "TH", "name": "Thailand", "region": "Asia", "flag": "th" },
{ "code": "VN", "name": "Vietnam", "region": "Asia", "flag": "vn" },
{ "code": "ID", "name": "Indonesia", "region": "Asia", "flag": "id" },
{ "code": "PH", "name": "Philippines", "region": "Asia", "flag": "ph" },
{ "code": "PK", "name": "Pakistan", "region": "Asia", "flag": "pk" },
{ "code": "BD", "name": "Bangladesh", "region": "Asia", "flag": "bd" },
{ "code": "RU", "name": "Russia", "region": "Europe", "flag": "ru" },
{ "code": "PL", "name": "Poland", "region": "Europe", "flag": "pl" },
{ "code": "PT", "name": "Portugal", "region": "Europe", "flag": "pt" },
{ "code": "IE", "name": "Ireland", "region": "Europe", "flag": "ie" },
{ "code": "AT", "name": "Austria", "region": "Europe", "flag": "at" },
{ "code": "DK", "name": "Denmark", "region": "Europe", "flag": "dk" },
{ "code": "FI", "name": "Finland", "region": "Europe", "flag": "fi" },
{ "code": "NO", "name": "Norway", "region": "Europe", "flag": "no" },
{ "code": "NZ", "name": "New Zealand", "region": "Oceania", "flag": "nz" },
{ "code": "IL", "name": "Israel", "region": "Middle East", "flag": "il" },
{ "code": "EG", "name": "Egypt", "region": "Africa", "flag": "eg" },
{ "code": "MA", "name": "Morocco", "region": "Africa", "flag": "ma" },
{ "code": "TN", "name": "Tunisia", "region": "Africa", "flag": "tn" },
{ "code": "DZ", "name": "Algeria", "region": "Africa", "flag": "dz" },
{ "code": "LY", "name": "Libya", "region": "Africa", "flag": "ly" },
{ "code": "SD", "name": "Sudan", "region": "Africa", "flag": "sd" },
{ "code": "SS", "name": "South Sudan", "region": "Africa", "flag": "ss" },
{ "code": "CD", "name": "DR Congo", "region": "Africa", "flag": "cd" },
{ "code": "AO", "name": "Angola", "region": "Africa", "flag": "ao" },
{ "code": "MZ", "name": "Mozambique", "region": "Africa", "flag": "mz" },
{ "code": "ZM", "name": "Zambia", "region": "Africa", "flag": "zm" },
{ "code": "ZW", "name": "Zimbabwe", "region": "Africa", "flag": "zw" },
{ "code": "BW", "name": "Botswana", "region": "Africa", "flag": "bw" },
{ "code": "NA", "name": "Namibia", "region": "Africa", "flag": "na" }, 
{ "code": "SZ", "name": "Eswatini", "region": "Africa", "flag": "sz" }, 
{ "code": "LS", "name": "Lesotho", "region": "Africa", "flag": "ls" }, 
{ "code": "MG", "name": "Madagascar", "region": "Africa", "flag": "mg" },
 { "code": "MU", "name": "Mauritius", "region": "Africa", "flag": "mu" }, 
 { "code": "SC", "name": "Seychelles", "region": "Africa", "flag": "sc" }, 
 { "code": "CV", "name": "Cape Verde", "region": "Africa", "flag": "cv" },
  { "code": "GM", "name": "Gambia", "region": "Africa", "flag": "gm" }, 
  { "code": "GW", "name": "Guinea-Bissau", "region": "Africa", "flag": "gw" }, 
  { "code": "GN", "name": "Guinea", "region": "Africa", "flag": "gn" }, 
  { "code": "SL", "name": "Sierra Leone", "region": "Africa", "flag": "sl" },
   { "code": "LR", "name": "Liberia", "region": "Africa", "flag": "lr" },
    { "code": "CI", "name": "Ivory Coast", "region": "Africa", "flag": "ci" }, { "code": "BF", "name": "Burkina Faso", "region": "Africa", "flag": "bf" }, { "code": "ML", "name": "Mali", "region": "Africa", "flag": "ml" }, { "code": "NE", "name": "Niger", "region": "Africa", "flag": "ne" }, { "code": "TD", "name": "Chad", "region": "Africa", "flag": "td" }, { "code": "CF", "name": "Central African Rep.", "region": "Africa", "flag": "cf" }, { "code": "GA", "name": "Gabon", "region": "Africa", "flag": "ga" }, { "code": "GQ", "name": "Equatorial Guinea", "region": "Africa", "flag": "gq" }, { "code": "ST", "name": "São Tomé & Príncipe", "region": "Africa", "flag": "st" }, { "code": "BJ", "name": "Benin", "region": "Africa", "flag": "bj" }, { "code": "TG", "name": "Togo", "region": "Africa", "flag": "tg" }, { "code": "SN", "name": "Senegal", "region": "Africa", "flag": "sn" }, { "code": "MR", "name": "Mauritania", "region": "Africa", "flag": "mr" }, { "code": "EH", "name": "Western Sahara", "region": "Africa", "flag": "eh" }, { "code": "SO", "name": "Somalia", "region": "Africa", "flag": "so" }, { "code": "DJ", "name": "Djibouti", "region": "Africa", "flag": "dj" }, { "code": "ER", "name": "Eritrea", "region": "Africa", "flag": "er" }, { "code": "BI", "name": "Burundi", "region": "Africa", "flag": "bi" }, { "code": "MW", "name": "Malawi", "region": "Africa", "flag": "mw" }, { "code": "KM", "name": "Comoros", "region": "Africa", "flag": "km" }] as const;

export type CountryCode = typeof COUNTRIES[number]['code'];
export const getCountryByCode = (code: string) => COUNTRIES.find(c => c.code === code);
export const getCountriesByRegion = (region: string) => COUNTRIES.filter(c => c.region === region);
